services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gemini_clone
    ports:
      - "5433:5432"  
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6380:6379"   

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env.docker
    ports:
      - "8000:8000"  
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: python worker.py
    env_file: .env.docker
    depends_on:
      - db
      - redis

volumes:
  db_data:
